import { Mock } from "mockjs";
let List = []
export default{
  getStatisticalData:()=>{
    for(let i =0;i<7;i++){
      List.push(
        Mock.mock({
          苹果:Mock.Random.float(100,8000,0,0),
          vivo:Mock.Random.float(100,8000,0,0),
          oppo:Mock.Random.float(100,8000,0,0),
          魅族:Mock.Random.float(100,8000,0,0),
          三星:Mock.Random.float(100,8000,0,0),
          小米:Mock.Random.float(100,8000,0,0)
        })
      )
    }
    return{
      code:20000,
      data:{
        videoData:[
          {
            name:"小米",
            value:2999
          },
          {
            name:"苹果",
            value:5999
          },
          {
            name:"小米",
            value:2999
          },
          {
            name:"小米",
            value:2999
          },
          {
            name:"小米",
            value:2999
          },
          {
            name:"小米",
            value:2999
          },
        ]
      }
    }
  }
}